version: '3'

services:
  db: 
    image: postgres 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cash
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    command: npm rum migrate
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app